export const SET_VIEW_NAME = "SET_VIEW_NAME";
export const SET_DATA_ALERTS = "SET_DATA_ALERTS";
export const SET_SELECTED_ALERT = "SET_SELECTED_ALERT";
export const SET_BUSY_STATUS = "SET_BUSY_STATUS";
